import AppKit
import Foundation

struct ClipboardHistoryItem: Identifiable, Equatable {
    let id: UUID
    let text: String
    var preview: String { String(text.prefix(160)) }
}

struct ClipboardSnapshot: Equatable {
    var text: String

    static let empty = ClipboardSnapshot(text: "")
}

final class ClipboardService: ObservableObject {
    @Published private(set) var snapshot = ClipboardSnapshot.empty
    @Published private(set) var history: [ClipboardHistoryItem] = []

    private let pasteboard: NSPasteboard
    private var lastChangeCount: Int
    private let historyLimit = 10

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    func refresh() {
        guard pasteboard.changeCount != lastChangeCount else {
            return
        }

        lastChangeCount = pasteboard.changeCount
        let excludedTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                             "org.nspasteboard.AutoGeneratedType"]
        guard !excludedTypes.contains(where: { pasteboard.types?.contains(NSPasteboard.PasteboardType($0)) == true }) else {
            snapshot = .empty
            return
        }
        let text = pasteboard.string(forType: .string) ?? ""
        addToHistory(text)
    }

    func copy(_ item: ClipboardHistoryItem) {
        guard history.contains(where: { $0.id == item.id }) else { return }
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        snapshot = ClipboardSnapshot(text: item.preview)
    }

    func clearHistory() {
        snapshot = .empty
        history = []
        lastChangeCount = pasteboard.changeCount
    }

    private func addToHistory(_ text: String) {
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.utf8.count <= 65_536 else {
            snapshot = .empty
            return
        }

        guard !containsSensitiveText(text) else {
            snapshot = .empty
            return
        }
        snapshot = ClipboardSnapshot(text: String(text.prefix(160)))
        history.removeAll { $0.text == text }
        history.insert(ClipboardHistoryItem(id: UUID(), text: text), at: 0)
        history = Array(history.prefix(historyLimit))
    }

    private func containsSensitiveText(_ text: String) -> Bool {
        let lowercased = text.lowercased()
        let sensitiveMarkers = [
            "password",
            "passwd",
            "token",
            "secret",
            "api_key",
            "apikey",
            "bearer ",
            "ghp_",
            "sk-"
        ]

        let sensitivePatterns = [
            #"AKIA[0-9A-Z]{16}"#,
            #"[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}"#,
            #"-----BEGIN [A-Z ]*PRIVATE KEY-----"#,
            #"[?&](token|key|secret|password|signature)=[^&\s]+"#,
            #"[A-Za-z0-9+/=_-]{48,}"#
        ]

        let hasSensitiveMarker = sensitiveMarkers.contains(where: lowercased.contains)
        let hasSensitivePattern = sensitivePatterns.contains { pattern in
            text.range(of: pattern, options: [.regularExpression, .caseInsensitive]) != nil
        }

        return hasSensitiveMarker || hasSensitivePattern
    }
}
